language: php

php:
    - 7.3
    - 7.4
    - 8.0

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer validate

install:
    - composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1
    - vendor/bin/phpunit
